#!/usr/bin/bash
# 
# zt - is a zettel selector using fzf
# This searches by tags
# features:
#  - it accepts multiple selection (using tab)
#  - copy multiple selection to clipboard (mapped to ctrl-y)
#  - clear selection (mapped to ctrl-l)
#  - populates (n)vim quickfix list with zettel titles (enter)
#

SRC_FOLDER=$HOME/programming/notes/notes

main() {
    cd "$SRC_FOLDER"
    grep --with-filename "^#[[:alnum:]]" *.md | sed 's/:/ | /g' |  fzf --tac --multi \
                                --layout=reverse \
                                --preview "echo {} | head | xargs bat --style=plain --color=always" \
                                --preview-window=wrap \
                                --bind '?:toggle-preview' \
                                --bind 'ctrl-l:clear-selection' \
                                --bind "ctrl-y:execute(printf '%s\n' {+} | xclip -selection clipboard)" \
                                --bind 'enter:execute(echo {+} | grep -o "[a-zA-Z0-9_-]\+\.md" | xargs -o vim -c "silent bufdo grepadd ^\#  %")'
}

main
